### ISSUE TITLE
SpotMAX would like to join as a community partner

### ISSUE THREAD

**Issue by ElpadoCan** [bioimage-io/collection#104]
### 1. Description of your software, organization, company or team

SpotMAX is a Python software for the analysis of multi-dimensional fluorescence microscopy data. 

- Preprint: https://www.biorxiv.org/content/10.1101/2024.10.22.619610v1
- Source code: https://github.com/SchmollerLab/SpotMAX
- Documentation: https://spotmax.readthedocs.io/en/latest/
- Logos: https://github.com/SchmollerLab/SpotMAX/tree/main/spotmax/resources

### 2. Description of the resources that you plan to contribute. Please also include the url to your project repo.

We plan to upload two U-Net models (one 2D and one 3D) trained on a large dataset of diffraction-limited spots. Additionally, SpotMAX can run the models from BioImage.IO and we will encourage users who train their own SpotMAX model to submit it as a resource on BioImage.IO. 

The training dataset is available here (permanent link with DOI coming soon): https://hmgubox2.helmholtz-muenchen.de/index.php/s/BFpbnnNGNFQCTk3

If possible, we would also like to contribute to BioImage.IO code development.

### 3. Description of future plans on how your project will be maintained.

SpotMAX is developed on top of our previously published software [Cell-ACDC](https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-022-01372-6). 

It has been primarily developed and maintained by me (Francesco Padovani) with funding ensured by the PI of the group, Kurt Schmoller.  It is already used by more than 15 research labs. Many of these labs (some of them are co-authors) already provided invaluable feedback to further improve our software. 

We are committed to maintaining SpotMAX for the years to come while applying for grants to keep it alive. It builds on top of the Cell-ACDC user base that counts over 100 active users. 

Thank you very much and congratulations on the incredible amount of work done so far, BioImage.IO is amazing 🚀

**Comment by ElpadoCan** [comment]
Hi @FynnBe, I started looking at the notebook on how to create my model to upload to the zoo and I have a question. The notebook creates a `ModelDescr` using the variable `model` that was created by loading an existing model.

However, my model is not existing yet, so how do I initialize `model` from scratch? Thank you very much!

**Comment by FynnBe** [comment]
> Instead, could we please wait for the dataset to be on a repository like EBI BioImage Archive with a permanent DOI? 

Of course, you can upload their descriptions whenever you're ready

**Comment by FynnBe** [comment]
![image](https://github.com/user-attachments/assets/e5bd715c-7c33-48ec-9569-032271314a36)
Welcome SpotMAX! 🎉

**Comment by FynnBe** [comment]
Small update: 
I have refactored the ilastik example to provide `script_utils.check_tool_compatibility`: https://github.com/bioimage-io/collection/blob/5327dac33314f6817f07e88c7b099110011d5831/scripts/script_utils.py#L48-L72

This simplifies the compatibility script needed from a partner, e.g. [ilastik example](https://github.com/bioimage-io/collection/blob/5327dac33314f6817f07e88c7b099110011d5831/scripts/check_compatibility_ilastik.py#L88-L95), so now almost only an analog to https://github.com/bioimage-io/collection/blob/5327dac33314f6817f07e88c7b099110011d5831/scripts/check_compatibility_ilastik.py#L16-L25
is needed to implement the compatibility check.

Hope this makes things easier now and more maintainable in the future!

**Comment by ElpadoCan** [comment]
Hi @FynnBe,

Thanks to the notebook you sent, I finally managed to package SpotMAX model into a ZIP archive that I will soon upload to BioImage.IO! Thank you very much for that! 

However, before I upload I just want to be sure everything is correct. When I call [`bioimageio.spec.save_bioimageio_package`](https://github.com/bioimage-io/spec-bioimage-io/blob/9983d3ede2b07e4348550b194f859d0038c91875/bioimageio/spec/_package.py#L179) I get the following warning, should I do something about it? Thanks! 

```shell
PydanticSerializationUnexpectedValue: Expected `TimeOutputAxis` but got `SpaceOutputAxis` with value `SpaceOutputAxis(size=43, ...', unit=None, scale=1.0)` - serialized value may not be as expected
  PydanticSerializationUnexpectedValue: Expected `TimeOutputAxisWithHalo` but got `SpaceOutputAxis` with value `SpaceOutputAxis(size=43, ...', unit=None, scale=1.0)` - serialized value may not be as expected
  PydanticSerializationUnexpectedValue: Expected `TimeOutputAxis` but got `SpaceOutputAxis` with value `SpaceOutputAxis(size=123,...', unit=None, scale=1.0)` - serialized value may not be as expected
  PydanticSerializationUnexpectedValue: Expected `TimeOutputAxisWithHalo` but got `SpaceOutputAxis` with value `SpaceOutputAxis(size=123,...', unit=None, scale=1.0)` - serialized value may not be as expected
  PydanticSerializationUnexpectedValue: Expected `TimeOutputAxis` but got `SpaceOutputAxis` with value `SpaceOutputAxis(size=167,...', unit=None, scale=1.0)` - serialized value may not be as expected
  PydanticSerializationUnexpectedValue: Expected `TimeOutputAxisWithHalo` but got `SpaceOutputAxis` with value `SpaceOutputAxis(size=167,...', unit=None, scale=1.0)` - serialized value may not be as expected
```

**Comment by FynnBe** [comment]
Thanks for reporting these warning messages!
I've encountered them and investigated these to some extent. All rount-trip tests I've added so far all pass regardless of these warnings. I created https://github.com/bioimage-io/spec-bioimage-io/issues/675 to keep track of this issue, but feel free to ignore it for now -- it hasn't causes any issue so far.

**Comment by ElpadoCan** [comment]
Great, I uploaded my first model! Thank you very much for all the support. I will soon upload a second model and eventually the dataset. Best, Francesco
