### ISSUE TITLE
Delete merged branch dont_skip_testing

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#11]
Is the dont_skip_testing branch finished @FynnBe ? It was merged a few days ago in #5  but not automatically deleted, just want to make sure before deleting...

**Comment by FynnBe** [comment]
interesting, locally I don't see it anymore after fetching all... 
and https://github.com/bioimage-io/collection/tree/dont_skip_testing
looks empty: 
![image](https://github.com/bioimage-io/collection/assets/15139589/a698c309-5188-4b36-964c-e8ae3bd85e6e)

**Comment by FynnBe** [comment]
also it is not listed in the "all branches overview"
![image](https://github.com/bioimage-io/collection/assets/15139589/f32846e6-88c3-4405-bc0c-0187fd63b97f)

**Comment by jmetz** [comment]
Aha yes - you're right, it's gone for me too; either i was viewing a stale/cached webpage or something I guess. Either way, yes resolved, thanks!
