### ISSUE TITLE
CI runtime too long 

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#13]
As mentioned in #6 (see in particular: https://github.com/bioimage-io/collection/issues/6#issuecomment-1975928835 ), the CI runtime can exceed 50 minutes. 

This is likely to become problematic considering the review cycle, and will cause scaling issues in terms of CI-runtime credit.

**Comment by jmetz** [comment]
@oeway - I have a feeling you'll recommend not worrying about this right now, but I thought it's worth opening this issue as it probably will be worth worrying about in the not very distant future! 

If @FynnBe is correct, this might be simply caused by download and upload speeds, in which case there wouldn't seem to be any quick fixes. 

Probably the only way to resolve this would be to everything after the initial zip upload happen within the same location...

**Comment by FynnBe** [comment]
yes, we can optimize a little using GH artifacts instead of uploading the unzipped package and redownloading the unzipped files (which is a bit cleaner/more straight forward though).
I'm not sure we have to worry about this at the moment at all, because for public repositories there is no limit of ci minutes/month, see https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration

or https://github.com/pricing
![image](https://github.com/bioimage-io/collection/assets/15139589/3da2c2b5-4175-4c58-a767-0ee02f238af1)

**Comment by jmetz** [comment]
:thinking: I might be misreading the pricing... but doesn't that mean that there are "2000 minutes free for public repos / per month" ? :sweat_smile:

**Comment by jmetz** [comment]
Also I just retried the upload (still the same error - messaged you via matrix about this @FynnBe ) - but the important thing is that the CI didn't seem to hang or take long this time at all ( https://github.com/bioimage-io/collection/actions/runs/8156407600 ) - just 2 mins total, so closing this for now. We can reopen if the problem returns.

**Comment by FynnBe** [comment]
> 🤔 I might be misreading the pricing... but doesn't that mean that there are "2000 minutes free for public repos / per month" ? 😅

Thought about that, too, but I don't think so. Thats why I linked https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration :

> GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage for use with GitHub-hosted runners, depending on the account's plan.

**Comment by jmetz** [comment]
Ahh you're right! I made the mistake of using runners (including the large-macos runner) on a private repo and quickly eating up all my free-usage allowance. Thanks for the info :+1:
