### ISSUE TITLE
Emoji/icon confusion (causing current uploader fails) 

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#14]
Is `id_emoji` supposed to be top-level in _rdf.yaml_?

In general there seems to be confusion in _collection_ wrt `id_emoji` and `nickname_icon`:

```sh
❯ rg 'nickname_icon'
scripts/upload_resource.py
157:        nickname_icon = rdf_base.pop("nickname_icon")
189:        rdf["id_emoji"] = nickname_icon
❯ rg 'id_emoji'
scripts/upload_resource.py
189:        rdf["id_emoji"] = nickname_icon

scripts/utils/remote_resource.py
75:        if rdf.get("id_emoji") is None:
76:            # TODO: set `id_emoji` according to id
77:            raise ValueError(f"RDF in {package_url} is missing `id_emoji`")

backoffice/remote_resource.py
186:        if rdf.get("id_emoji") is None:
187:            # TODO: set `id_emoji` according to id
188:            raise ValueError(f"RDF in {package_url} is missing `id_emoji`")
```

Could you clarify what you want in the **RDF** (and where) wrt to emoji/icon please @FynnBe ?

At the moment in the client code I only create nickname as a string of the name without the icon, on the top level of the RDF.

**Comment by jmetz** [comment]
And a related follow-on question: do you want `RDF.nickname` -> `RDF.id` ?

**Comment by FynnBe** [comment]
The script is not intended for use beyond conversion of the current collection to the new:

> """This script was used internally to upload previously contributed resources to bioimage.io that were managed through the old bioimage-io/collection-bioimage-io repo"""

`RDF.nickname` has never been an official field.
Now we will have `RDF.id` which is set to the animal nickname for the current collection

**Comment by FynnBe** [comment]
ah, I still missed the clarification part, sorry:
So from now on (with the soon to be released spec library) we will have an (RDF.)`id` and `id_emoji` field in root

**Comment by FynnBe** [comment]
can we close this issue then @jmetz ?

**Comment by jmetz** [comment]
Yes - that's perfect thanks!

**Comment by jmetz** [comment]
PS I'll have to remove those from the old pyodide validator like I did for the `uploader` field  - until the pyodide-based validator can support the new spec (or there's a new option for that).
