### ISSUE TITLE
Should review processes (`publish`, `request_changes`) include eg `reason` or should all _correspondence_ be pushed to the chat mechanism? 

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#26]
At present, `request_changes` action has a (non optional) `reason` parameter, and `publish` has no additional message-type parameters.

Perhaps it would make more sense for all messages (including an optional `request_changes` reason to end up in the chat as messages instead? Could be cleaner that way.

**Comment by FynnBe** [comment]
I would like to keep the mandatory 'reason' for requesting changes. one might wonder later why changes were requested and then it can be tedious to have to search the chat. but we can additionally show it in the chat. how about that?
In general status update/generated logs should stay out of the chat, which is somewhat reserved for human messages, but for request changes and publish we can add short messages to make it easier to follow the chat flow.

**Comment by FynnBe** [comment]
closing this for now (current state: request_changes has a `reason`; system messages for `request_changes` and `publish` are added to the chat)
