### ISSUE TITLE
Add check of reviewer email

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#29]
In the review service I added a mechanism to check the user/reviewer against a list of allowed reviewers (adapted from the chatbot) :  https://github.com/bioimage-io/bioimageio-uploader-review/blob/main/bioimageio_upload_review/api.py#L100-L127

NB I also plan to update that code to load the list from a url instead of local file. 

Should we instead have this be baked into `bioimageio-collection-backoffice`? The benefit would be that this then gets done for both CI publish workflows as well as direct use of `bioimageio-collection-backoffice`.

**Comment by FynnBe** [comment]
yeah, I can add a helper function (and use that for validating reviewer strings) 
should we allow a reviewer name or only a reviewer email?

**Comment by jmetz** [comment]
We just need to decide on where to fetch the "authorized_reviewers" list from - it _could_ be a file in the same repo, if we go with @oeway 's suggestion. Alternatively it could be a private S3 file... Though then updating it becomes a tiny bit more involved. 

A third option would be an additional _private_ repo (within BioimageIO). 

From a security perspective, it would probably make more sense for that list to be private.

**Comment by FynnBe** [comment]
but the reviewer's email is being published anyway (e.g. as "reviewer@email.com has accepted funky-fish staged/3")
so I guess we can have it public too

**Comment by jmetz** [comment]
Hmm good point... Though having the full list of all reviewers be public is probably worse than being able to reconstruct that information slowly over time by looking at all the review logs. 

Nonetheless, it's a fair point. Perhaps for now then, having the list as a simple JSON file in this repo is ok.

**Comment by FynnBe** [comment]
as discussed in today's meeting we'll use a mapping github account names to names in this repo.
reviewer are identified by their github user name (hypha login should return id and email)

**Comment by oeway** [comment]
To clarify, it will have an id in the user dictionary in hypha service functions for Google/github or hypha account.

**Comment by FynnBe** [comment]
For now we require reviewers to login with their GithHub account, account name to display name (and who is a reviewer at all) is defined at https://github.com/bioimage-io/collection/blob/main/reviewers.json.
Expanding on this is not high priority right now.
