### ISSUE TITLE
Add user id to the reviewer list.

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection#36]
FYI: We will need to add the actual user id, not just the github id to the reviewer list to check against.

For example my github id is `oeway` and the user id is `github|478667`, to get the id, you can login with your github or other account here: https://ai.imjoy.io/public/apps/hypha-login/

@FynnBe @jmetz what are your id?

**Comment by jmetz** [comment]
Mine's: `github|1950756`

**Comment by jmetz** [comment]
Also for future reference for others, you can also use eg : 

https://api.github.com/users/jmetz 

Benefit is not needing to signin / we could use this to add id's for people automatically with a simple few-line script.
