### ISSUE TITLE
Make eg `chat` and `review` functionalities cleaner wrt "staging" vs "published"

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#38]
From matrix chat with @FynnBe :

> Quick Q: just working on chat and review: was the idea to set `"staged"` or `"published"` in the resource_id or the version? 

> as there's no flag for that, and my chat function fails as it's trying to chat to eg `"frank-water-buffalo/1/chat.json"` 

> I can see that either using `resource_id =  "frank-water-buffalo/staged"` or `version =  "staged/1"` could work...

> ... it seems to me (as a potential future enhancement) that this should be handled in the internals of "add_chat_message", not as a potentially failing input...   

## Recommendation

> eg we could `update _backoffice.Backoffice.add_chat_message` to have the following signature: `add_chat_message(self, resource_id: str, staging: bool, version: str, chat_message: str, author: str)` or similar

> that way, anything using `Backoffice` (or even calling the CI) doesn't need to know how staging / vs published are handled, and won't break if that changes

> (alternatively instead of the staging bool, we could have some enum if we want to allow the possibility of eg "retracted" or something in the future 😅)

**Comment by FynnBe** [comment]
answer from matrix chat:
> Staged version numbers are somewhat independent of published ones... So if we would use a bool. The version input does not have the same semantic meaning depending on that flag ... 
I don't see the issue with using version "staged/1"  it's just that we skip published in published/1

closing for now
