### ISSUE TITLE
`add_chat_message` time issue  

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#39]
Seems that `add_chat_message`'s use of `datetime.now` gets stuck in the past! 

![image](https://github.com/bioimage-io/collection/assets/1950756/a620daa7-4da7-49d9-916f-148b799d52d0)

I _think_ this issue might actually be with `hypha` (@oeway - could you confirm this?), in which case we should link this to an issue there... in fact this issue could be replicated between the `hypha` repo and the `bioimageio-uploader-service` too. 

Presumably this is because of the way that `hypha` creates its remote functions or something... but am not sure.

**Comment by oeway** [comment]
I don't know how chat works, but it doesn't make sense to me that this will related to hypha, it's just a communication after all. Could you elaborate why this will related to hypha? Please include link to related code. @jmetz

**Comment by jmetz** [comment]
Sure, it's in the `bioimageio-uploader-service` here: 

https://github.com/bioimage-io/bioimageio-uploader-service/blob/main/bioimageio_uploader_service/api.py#L163-L175

```
    async def chat(resource_id: str, version: str, message: str, context=None):
        logger.info(f"User: {context.get('user')}, Message: {message}")
        if check_context_permission(context) < Permission.LOGGED_IN:
            raise PermissionError("You must be logged in to comment on the review")

        chat_data = ChatData(
            resource_id=resource_id,
            version=version,
            message=message,
            user=context.get("user"),
            )

        chat_data.save(backoffice)

```

The reason that this is done as a Hypha Service is that I check that a user is logged in before updating the `chat.json` via `Backoffice`... and the client wouldn't have S3 write access anyway.

**Comment by oeway** [comment]
That I get, I mean I don't get where the date.time() was passed to the chat service, you passed in `resource_id: str, version: str, message: str`, but I don't see the time. If the function get called properly, I don't see why the bug has to do with hypha itself. Or I missed anything?

**Comment by jmetz** [comment]
Ahh right I see what the confusion was, from the above, when `ChatData` is instantiated, it should be calling it's parent class ' __post_init__` (as I used `dataclasses`): 
 
```python
@dataclass
class ResourceData:
    resource_id: str
    version: str
    user: str
    timestamp: str = field(init=False)

    def __post_init__(self):
        self.timestamp = str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

...

@dataclass
class ChatData(ResourceData):
    message: str

    def save(self, backoffice: BackOffice):
        backoffice.add_chat_message(
                resource_id=self.resource_id,
                version=self.version,
                chat_message=self.message,
                author=self.user)
```

So as far as I can tell, that `__post_init__` should run within the `chat` service function, and the datetime should be accurate, but for some reason it seems to correspond to when the `bioimageio-uploader-service` gets started.

**Comment by jmetz** [comment]
Oh wait... I see now maybe...lemme check...

**Comment by jmetz** [comment]
Ahh yeah my timestamp code is totally pointless, sorry about that. It doesn't get passed in. Instead, in this repo we have: 
https://github.com/bioimage-io/collection/blob/main/bioimageio_collection_backoffice/_backoffice.py#L148-L157

```python
    def add_chat_message(
        self, resource_id: str, version: str, chat_message: str, author: str
    ):
        chat = Chat(
            messages=[
                Message(author=author, text=chat_message, timestamp=datetime.now())
            ]
        )
        rv = get_remote_resource_version(self.client, resource_id, version)
        rv.extend_chat(chat)
```

**Comment by jmetz** [comment]
@oeway : Any thoughts given my (slightly round-about) explanation above? 

To recap, 
* in my service I added code to create a timestamp, but this actually *does not get used*
* the timestamp is set in `bioimageio_collection_backoffice._backoffice.BackOffice.add_chat_message` as explained in the last message

As this is called on each new chat request, by my service (https://github.com/bioimage-io/bioimageio-uploader-service/blob/main/bioimageio_uploader_service/api.py#L163-L175), it *should* have timestamp that is set each time the chat service function is called... so I don't understand why all chats seem to have the same timestamp. 

I'll check through this codebase again, but if it is not there, could the issue be in Hypha? Does it do some kind of caching of function objects or something :sweat_smile: ?

**Comment by oeway** [comment]
Hi, could you print the message before calling hypha `chat` function on the frontend, and after calling that function in the hypha service? To check if it's a hypha issue, we just need to compare that, right? We don't have any caching in hypha, so it doesn't make sense to me that hypha will change anything.

Also it seems you set `timestamp: str` but then you `timestamp=datetime.now()` which does not have string type.
