### ISSUE TITLE
Use `user_ids` as keys in `reviewers.json` or change some internal logic in `collection`?

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#41]
Am just working to get the review working, and have hit the following permission error from this project: 

```
Traceback (most recent call last):
File "bioimageio_uploader_service/api.py", line 186, in review
    review_data.save(backoffice)
  File "bioimageio_uploader_service/api.py", line 68, in save
    backoffice.request_changes(resource_id=self.resource_id, version=self.version, reviewer=self.user_id, reason=self.message)
  File "bioimageio_collection_backoffice/_backoffice.py", line 107, in request_changes
    rv.request_changes(reviewer=reviewer, reason=reason)
  File "bioimageio_collection_backoffice/remote_resource.py", line 374, in request_changes
    reviewer = REVIEWERS[reviewer.lower()].name  # map to reviewer name

KeyError: 'github|1950756'
```

Clearly then this is because the `keys` in this JSON are still the github _usernames_, while the `user_id` was entered as a key for each user entry. 

We have two options IMO: 

a) Change the backend logic to do the same checking over the fields
b) Change the file format so the the `user_id` becomes the key

What are your preferences here @oeway + @FynnBe ?

**Comment by jmetz** [comment]
Eg the permission check would become: 

```python
    # reviewer = REVIEWERS[reviewer.lower()].name
    # to 
    reviewer = [item for item in REVIEWERS if reviewer == item.user_id].name
    
```
(or similar)

**Comment by oeway** [comment]
I would go for 2) so the user_id become the key.

**Comment by jmetz** [comment]
@FynnBe - Is Wei's suggestion to bake the `user_id` become the key ok - will it break anything in how the rest of collection works (ie do you check the key somehow to see if it's a valid _github username_?

**Comment by jmetz** [comment]
Closing with #42

**Comment by FynnBe** [comment]
Yes it breaks things. WFs (in a pending pr) are called  with the 'github.actor' var
