### ISSUE TITLE
[question]: Emailing from eg uploader service function 

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#43]
@oeway : Are you happy for the uploader service function (that will run alongside Hypha) to do emailing? 

This is part of eg the publish and request-changes functionalities. 

The alternative would be to revert to kicking off the CI workflows for these actions... but other than the emailing, they only write to S3, so I had wanted to do that from the service function.

**Comment by oeway** [comment]
Having the email in hypha service function make sense, then you can also send email when a reviewer made a comment, right?

**Comment by jmetz** [comment]
Yes that's the idea; the two cases when an email is sent is "publish" or "request-changes". I'm not sure that emails should be send whenever a reviewer generally chats though... right?

**Comment by oeway** [comment]
> Yes that's the idea; the two cases when an email is sent are "publish" or "request-changes". I'm not sure that emails should be send whenever a reviewer generally chats though... right?

Right, if you have a request changes, it will work well enough for the review process.

However, depending on how you implement this right now, in the future versions, we should support user asking question about the model, this will be sent to the model maintainer as a notification.

**Comment by jmetz** [comment]
@FynnBe - could you share the SMTP creds with me on matrix please?
