### ISSUE TITLE
Write the run_id to staged log

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#59]
In the workflow of the collection CI, write the run_id (https://docs.github.com/en/actions/learn-github-actions/variables) to staged log, then get it from the client, so we can display it to the reviewer for the CI status

Relates to https://github.com/bioimage-io/bioimageio-uploader/issues/77

which is part of 

https://github.com/bioimage-io/bioimageio-uploader/issues/65

**Comment by FynnBe** [comment]
the run_id is part of the status as (`run_url`) , which is saved to versions.json, see https://bioimage-io.github.io/collection/bioimageio_collection_backoffice/db_structure/versions.html#_StatusBase.run_url

should I log them in addition?

**Comment by jmetz** [comment]
Think the url is enough - thats great thanks.

Does it save multiple `run_url`s per version or just the latest? In principle multiple runs could happen on the same version, right?

**Comment by FynnBe** [comment]
one per version (so if a test is running the run_url of the staging process will no longer be available, because it is now pointing to the test run)

**Comment by FynnBe** [comment]
then I would add them to the log where we can keep this kind of history. (I don't want to clutter versions.json with status history)

**Comment by FynnBe** [comment]
ok @jmetz ?

**Comment by jmetz** [comment]
Ah I see, yep, that sounds good. So new log context things - so we can even tell which ones are test logs etc, right?

**Comment by jmetz** [comment]
I saw you already have "bioimageio-core" and "..spec" contexts
