### ISSUE TITLE
CI workflow dispatch gets stuck

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#6]
After calling the `workflow_dispatch` and it failing for a reason that is well understood, it seems to get stuck and not end: 

![image](https://github.com/bioimage-io/collection/assets/1950756/b837e796-fedf-45d7-9aaf-dbf53c0fa630)

The logs:

![image](https://github.com/bioimage-io/collection/assets/1950756/da9aa841-68a9-4a36-8935-962bade24954)

![image](https://github.com/bioimage-io/collection/assets/1950756/9d60b6bc-26fa-4dc7-a3fa-7aa8bd028317)

I manually cancelled the job after 15 minutes to avoid unnecessarily eating all the CI time... which unfortunately seems to have deleted the logs.

**Comment by FynnBe** [comment]
stage #4 does not look like it's been cancelled and the `conclude` step finished successfull.
Are you sure it was stuck? Some of these CI processes are just slow, e.g. successfull stage #4 run ran for 54 minutes: https://github.com/bioimage-io/collection/actions/runs/8047037363

**Comment by jmetz** [comment]
The issue is that it definitely failed - there was a traceback in the log window, and as you can see in the screenshot it thinks it gets to be cleanup stage, but then it just sits there for close to 15 minutes... Seems problematic to me at least.

Also if we have relatively simple validation and unzipping operations that use >50 mins of CI time... I mean for now we might be ok with such a low volume of resource submissions (once I stop submitting things to test 😅), but overall this seems like way too long to me!

**Comment by FynnBe** [comment]
Definitely. It was the `backoffice stage` call that took so long and that one is pretty much bound by down and upload speed. ambitious-sloth has around 700MB of data.
