### ISSUE TITLE
Missing collection_staged.json in sandbox folder 

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#63]
As suspected, this bug is due to a missing file:

https://uk1s3.embassy.ebi.ac.uk/public-datasets/sandbox.bioimage.io/collection_staged.json

does not exist, whereas:

https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io/collection_staged.json

_does_ exist. 

@FynnBe - would you consider this a [`collection`](https://github.com/bioimage-io/collection)  issue then?

_Originally posted by @jmetz in https://github.com/bioimage-io/bioimageio-uploader/issues/85#issuecomment-2089984683_

**Comment by jmetz** [comment]
Presumably this is just because nothing's been staged since this change was made / it's an easy fix - right @FynnBe ?

**Comment by FynnBe** [comment]
yeah.. I suppose I should unify the whole sandbox mode in the backend a bit and have a clean separate sandbox instance insetad of a series of sandbox flags...

**Comment by jmetz** [comment]
Hmm not sure about that ... Or at least it needs to be done carefully, as you probably want to use the same python module in both (and not a copy).. so if you did create a separate sandbox repo, it should utilise the code from this repo, right?

**Comment by FynnBe** [comment]
we are using 3 different github environments now: production, sandbox and testing.
many dispatch workflows have a sandbox flag (default: False) to use the sandbox instead.

the production and sandbox environemnts maintain full collections at https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io and https://uk1s3.embassy.ebi.ac.uk/public-datasets/sandbox.bioimage.io, respectively.
