### ISSUE TITLE
reviewers.json is missing

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection#67]
In the uploader service, we refer to the reviewers.json: https://github.com/bioimage-io/bioimageio-uploader-service/blob/79639755ed6882198db56824a99d944be08e3fc0/bioimageio_uploader_service/api.py#L150

Where should we get it @FynnBe

**Comment by FynnBe** [comment]
it's not under "reviewers" in https://raw.githubusercontent.com/bioimage-io/collection/main/bioimageio_collection_config.json
