### ISSUE TITLE
`bioimageio.core.test_model` passes but GitHub CI fails

### ISSUE THREAD

**Issue by qin-yu** [bioimage-io/collection#79]
Expected behaviour: if local test passes, then GitHub Actions should encounter no error.

My test:

![image](https://github.com/bioimage-io/core-bioimage-io-python/assets/17722010/3d0cf36e-dcaa-434d-9c5e-636b22ca56fa)

GitHub Actions: https://github.com/bioimage-io/collection/actions/runs/9515502505/job/26230316192

**Comment by qin-yu** [comment]
Thanks Fynn, I updated the env file for state dict and traced a CPU only torchscript. Not sure how to upload again.

**Comment by FynnBe** [comment]
just go to https://bioimage.io/#/ and click `upload` in the upper right corner:
https://bioimageio-uploader.netlify.app/#/uploader/add
(with `id: philosophical-panda` (in the RDF) to update your previous upload)

**Comment by FynnBe** [comment]
btw, I think I fixed all default pytorch envs.

**Comment by qin-yu** [comment]
For identical environments with identical packages, versions, and even build (except the build for `libxml2`), local CI passes while online version fails. See #84

**Comment by FynnBe** [comment]
closing in favor of #84
