### ISSUE TITLE
PyTorch version `2.3.1` is converted to `2.3.1+cu121` automatically but CI doesn't use GPU

### ISSUE THREAD

**Issue by qin-yu** [bioimage-io/collection#83]
1. All of `pytorch_version: 2.3.1`, `pytorch_version: 2.3.1+cpu`, or `pytorch_version: 2.3.1+cu121` will make installation of PyTorch fail, which is fixed by Fynn already.
2. I think it complicates things if PyTorch version `2.3.1` is converted to `2.3.1+cu121` automatically by packaging when CI doesn't make use of GiHub Actions' GPU feature. Either of these should change.

```
bioimageio-core           0.6.7                    pypi_0    pypi
bioimageio-spec           0.5.3.post4              pypi_0    pypi
```

**Comment by FynnBe** [comment]
Do the tests fail with those versions running in CI?
Have you tried adding the `cpuonly` package to the dependencies? (see https://pytorch.org/get-started/locally/)

**Comment by qin-yu** [comment]
The memories are vague. Maybe it doesn't cause failed tests. But I was saying for CIs the code should either use GPU packages on GPU-enabled CI machines, or use CPU-only packages on traditional CI machines.

**Comment by FynnBe** [comment]
For conda default environments in case only a pytorch version is given the `cpuonly` package is specified: https://github.com/bioimage-io/collection/blob/4087336ad00bff0198f5de83c94aa13be357840d/bioimageio_collection_backoffice/conda_env.py#L138

for model uploads that do specify a conda environment that may not be the case, but I'd rather not mess with those environments contributed by users as long as the CI passes.

closing for now. We'll visit this topic again when also running CI with GPUs eventually...
