### ISSUE TITLE
Resource folder needs to have a `versions.json` file created right from the start

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection#9]
A failed run produced the following layout in S3: 

``` 
sandbox.bioimage.io/sociable-raccoon/
└── staged
    └── 1
        └── details.json

3 directories, 1 file
```

As discussed in #7, having this layout it desired for now, but in that case **we need** to have a root `versions.json` file created as soon as the first `staged` file exists also, so that clients can easily determine which version to query for details. 

## Proposed change

Create the root `versions.json` file at the same time as the initial `details.json` file, listing the first staged version. Potentially it could also hold the S3 link to the `details.json` for each version (staged and published) - what do you think @oeway @FynnBe ?

**Comment by FynnBe** [comment]
Creating root versions.json right away makes sense.
But urls of details.json files is deterministic, so I don't see why we would have to include it in the versions.json files.

**Comment by jmetz** [comment]
The rationale would be that that should mean that clients don't need to keep track of _how_ the backend does it's thing (ie what "folder" layout we're using). The root files would correspond to something more like the API in that case. Instead, at the moment the clients need to know all the details of the S3 layout to work properly (and be updated if that changes) - to deterministically build the URLs as you point out.

I'm not convinced that my suggestion is necessary/the best idea either though, so am happy to stick with things the way they are. The above reasoning just occurred to me as a way of achieving some sort of pseudo API backend when we're using the system we're using. 

The main drawback to my suggestion that I can see, is that the versions.json files themselves would need to be updated if the internal layout changes, but at least we have full control over them.

**Comment by jmetz** [comment]
PS one alternative is use netlify functions as the API instead... though comes at the cost of an extra leg each requests journey.

**Comment by FynnBe** [comment]
I'm not sure about this.
The client needs to know about the "details" key inside the versions.json instead of the S3 path to the details.json.
Even if we have links in the versions.json we cannot stop anyone from simply assuming the path to the details.json as they will follow a pattern. generating random keys to force people to read the details url from the verisons.json seems silly.
Not adding redundant links to the details.json seems like promoting a single source of truth. at least now everyone is using the S3 path to get to the details and there cannot be conflicting information in the versions.json.

**Comment by FynnBe** [comment]
considering that `details.json` has only `messages` and `status` I'm thinking we can move `status` into versions.json and have a more descriptive `chat.json` to hold messages and don't have any `details.json` at all.
Status is really different for staged and published versions: staged can be "unknown", "staging", "testing", "awaiting review" whereas published can be "published" (and maybe "retracted"??)
for now I would add status for published as well saying "published" and that's it.

I'll make a draft PR with these changes
