### ISSUE TITLE
BiaPy checks failing

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/collection#90]
@danifranco the new biapy checks seem to run into some issues when actually checking the models in the zoo:
https://github.com/bioimage-io/collection/actions/runs/10366799925/job/28696868334

Any idea what's going wrong there? Could you please fix it?

**Comment by FynnBe** [comment]
Just found some trivial issues that I try to fix in  https://github.com/bioimage-io/collection/commit/746ebef425762538c58d407a49488bfe8584922c

**Comment by danifranco** [comment]
Solved in https://github.com/bioimage-io/collection/commit/ea86bf6dbc5a65a2c55a2c6bcf4d11b21f622b22 . We also fixed a few issues when checking models in last BiaPy's realease [v3.5.1](https://github.com/BiaPyX/BiaPy/releases/tag/v3.5.1). Seems that the CI is working now: https://github.com/bioimage-io/collection/actions/runs/10416642296  

Also I can see now BiaPy icon in the model cards:
![image](https://github.com/user-attachments/assets/a65e71fe-5d6e-4969-b803-363d7f6191fc)

There is no BiaPy icon in `affable-shark` model for some reason even if the checks passed correctly (I checked the .json generated). I know that model is being used for testing new code so maybe something is different or needs to be updated: just to let you know.

**Comment by FynnBe** [comment]
I regenerated the collection json and test summary files and now it should appear (now there is an entry in `test_summary.yaml`, the website does not work for me atm, so I can't check it there)
But it seems that the biapy compatibility report was just not yet available an hour ago when the collection json and test summary files were generated last. 

So great that they are there now! BiaPy compatibility checks are online!
