### ISSUE TITLE
CI stopped due to error "System.IO.IOException: No space left on device"

### ISSUE THREAD

**Issue by mese79** [bioimage-io/collection#93]
I have a model uploaded, but at `pytorch_state_dict` test it stopped with this error:
```
System.IO.IOException: No space left on device : '/home/runner/runners/2.319.1/_diag/Worker_20240829-130542-utc.log'
```

You can see the CI here:
https://github.com/bioimage-io/collection/actions/runs/10613914843

I'm not sure if the test server capacity became full or if there is something wrong with the model.
The local tests are successful.

**Comment by FynnBe** [comment]
it seem like the limit for GH actions workflows is 14GB in our case:
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
The uploaded weights file `model_weights.pth` for plucky-goat/draft has only 2KB, so it seems to have failed during upload somehow?

how big is the model you tried to upload?

**Comment by FynnBe** [comment]
@oeway should we maybe warn uploaders of that size limit?
we should test how big the limit actually is in practice.
But as it seems to be below 14GB we might need to think about alternatives to bump that limit

**Comment by FynnBe** [comment]
that would be one of the alternative (or paying for higher tier GH actions) or using another "free tier" provider.

We did consider this server approach in the past. It does incur an additional maintenance burden. so it would be nice to get away with using GH actions... not sure what other ways there are to circumvent the disk space issue...

**Comment by oeway** [comment]
@FynnBe @mese79 Could you explain to me what exactly is the issue? In the previous message you said it's a small weight file, and it was working before even with big weight files, what has changed?

We are setting up a cluster at KTH which can helpfully used for running tests. @FynnBe I am not following the development of the core library, is it possible that I spin up a docker container, and just run the bioimage.io core library to run `bioimageio test-model <MODEL>`? Can it run all the models? We need several conda env? Maybe it's a bit tricky to build conda env on the fly though.

**Comment by mese79** [comment]
Sorry @FynnBe I missed your first comment.  
So I needed to upload a *Cellpose* model and as a workaround I've made a wrapper model which inside its `forward`  method I call the Cellpose API which downloads the Cellpose weight.  But even those weights are small (maybe ~50Mb).

**Comment by FynnBe** [comment]
I think the error was actually triggered when installing a large conda environment (that included cuda).
cpuonly environments should not face this issue... I'm closing this issue for now, please reopen if it happens again (for a non-gpu environment as well..)
