### ISSUE TITLE
Error in CI during upload for tensorflow_saved_model_bundle

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection#96]
I am trying to test with a new upload, however, got the following error:
```
call / test (tensorflow_saved_model_bundle)ENOENT: no such file or directory, lstat '/home/runner/work/_temp/setup-micromamba/micromamba-shell'
--
call / test (tensorflow_saved_model_bundle)The process '/home/runner/micromamba-bin/micromamba' failed with exit code 1

[call / test (tensorflow_saved_model_bundle)](https://github.com/bioimage-io/collection/actions/runs/11050494500/job/30698428600#step:17:5)
ENOENT: no such file or directory, lstat '/home/runner/work/_temp/setup-micromamba/micromamba-shell'
[call / test (tensorflow_saved_model_bundle)](https://github.com/bioimage-io/collection/actions/runs/11050494500/job/30698428600#step:4:347)
The process '/home/runner/micromamba-bin/micromamba' failed with exit code 1
```

Here is the job triggered by the uploader: https://github.com/bioimage-io/collection/actions/runs/11050447109/job/30698213109

Here is the error: https://github.com/bioimage-io/collection/actions/runs/11050494500

**Comment by FynnBe** [comment]
This is not a real issue as it only affects post run cleanup of the conda environment used during testing (but the job finishes afterwards anyway).
To remove the error annotation I created #97

**Comment by FynnBe** [comment]
still not actually fixed, but leaving closed in favor of #94

**Comment by oeway** [comment]
Is it only a clean up issue, the CI fails if you see from the status page: https://bioimageio-uploader.netlify.app/#/status/poisonous-raccoon

**Comment by FynnBe** [comment]
yeah, we should stop displaying the CI status badge there so prominently I suppose...  the fact that the message was logged means the CI ran successfully (until that point anyway).
But yeah, if CI fails we would also want to know about it if it relates to a model.
Not sure how to improve it, but the distinction of validation result and CI run status is not clear as it is now.
